### PR TITLE
Add jupyter_client as dependency to meta.yml

### PR DESCRIPTION
**Pull request by m-rossi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

During a development install of one of our internal packages I noticed the requirement of the conda package does not match the requirements of the pypi-package

### CODE REVIEW

**Comment by m-rossi** [comment]
@conda-forge-admin, please rerender

**Comment by jtpio** [comment]
Thanks @m-rossi!

Did you notice any issue with `jupyter_client` 7? If so would you like to comment on the upstream issue? https://github.com/voila-dashboards/voila/issues/941

**Comment by m-rossi** [comment]
I have not noticed any issues. As I said above, I just noticed the dependency issue because as I installed an internal package as editable in an conda environment without requirements (`pip install --no-deps -e .`). A console-script uses [setuptools-scm](https://pypi.org/project/setuptools-scm/) and that seems to check the dependencies in `setup.py` and raised an error.

**Comment by jtpio** [comment]
Alright thanks for the heads-up :+1: 

Probably we can then relax the pin upstream then.

**Comment by jtpio** [comment]
Thanks!

**Pull request merged**
